image: centos:centos7
 
before_script:
     - mkdir -p ~/.ssh
     - echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
     - chmod 600 ~/.ssh/id_rsa
     - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
 
deploy:
  image : panubo/sshd
  script:
    - ssh -i ~/.ssh/id_rsa root@$IP_SERVER "bash /home/siakad2/.scripts/sysch.sh"